services:
  comm_software:
    container_name: comm_software
    stdin_open: true
    tty: true
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: inspirers/communication-software:latest
    command: bash -c "source /root/atos_ws/install/local_setup.bash ; ros2 run communication_software run_main"
    network_mode: "host"