services:
  comm_software:
    container_name: comm_software
    # ipc: host
    # privileged: true
    stdin_open: true
    tty: true
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "source /root/atos_ws/install/local_setup.bash ; ros2 run communication_software run_main"
