name: Build and Push Docker Image

on:
  push:
    branches: [main]
    tags: [v*]  # Trigger on tags starting with 'v' (e.g., v1.0.0)

env:
  # Docker Hub username/image name.  IMPORTANT: Change this!
  IMAGE_NAME: your_dockerhub_username/communication-software

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # permissions:  <-- Remove 'packages: write' (not needed for Docker Hub)
    #   contents: read
    #   packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io  # Specify Docker Hub (optional, it's the default)
          username: ${{ secrets.DOCKER_HUB_USERNAME }}  # Use a secret for username
          password: ${{ secrets.DOCKER_HUB_TOKEN }}    # Use a secret for the token

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./communication_software # Directory *containing* the Dockerfile
          # file: ./communication_software/Dockerfile  <-- No longer needed, context is sufficient
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest