name: Build and Push Frontend Docker Image

on:
  push:
    branches: [main]
    tags: [v*]  

env:
  IMAGE_NAME: ghcr.io/inspirers/astazero-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io  
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD_TOKEN }}   

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile-prod
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
